In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn import tree

In [2]:
df = pd.read_csv("usda_data.csv")
df

,CensusTract,Urban,Pop2010,OHU2010,LILATracts_1And10,LILATracts_Vehicle,HUNVFlag,LowIncomeTracts,PovertyRate,MedianFamilyIncome,...,lasnap1share,TractLOWI,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV
0,1001020100,1,1912,693,0,0,0,0,11.3,"$81,250.00",...,13.22,455.0,1622.0,217.0,14.0,0.0,14.0,45.0,44.0,6.0
1,1001020200,1,2170,743,1,0,0,1,17.9,"$49,000.00",...,12.95,802.0,888.0,1217.0,5.0,0.0,5.0,55.0,75.0,89.0
2,1001020300,1,3373,1256,0,0,0,0,15.0,"$62,609.00",...,5.87,1306.0,2576.0,647.0,17.0,5.0,11.0,117.0,87.0,99.0
3,1001020400,1,4386,1722,0,0,0,0,2.8,"$70,607.00",...,1.76,922.0,4086.0,193.0,18.0,4.0,11.0,74.0,85.0,21.0
4,1001020500,1,10766,4082,0,0,1,0,15.2,"$96,334.00",...,2.04,2242.0,8666.0,1437.0,296.0,9.0,48.0,310.0,355.0,230.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52537,56041975400,0,6852,2632,0,1,1,1,17.3,"$57,248.00",...,3.39,2273.0,6160.0,20.0,19.0,2.0,67.0,584.0,871.0,124.0
52538,56043000200,0,3326,1317,0,0,0,0,9.7,"$67,254.00",...,3.82,765.0,3106.0,6.0,15.0,0.0,27.0,172.0,309.0,61.0
52539,56043000302,1,2542,1021,0,0,0,0,16.3,"$69,605.00",...,0.45,789.0,2312.0,11.0,10.0,1.0,26.0,182.0,407.0,23.0
52540,56045951100,0,3314,1322,0,0,0,0,17.5,"$74,500.00",...,1.59,955.0,3179.0,15.0,10.0,1.0,47.0,62.0,91.0,47.0
52541,56045951300,1,3894,1699,0,0,0,0,17.3,"$76,838.00",...,2.20,1095.0,3706.0,6.0,10.0,2.0,44.0,126.0,125.0,34.0

In [3]:
target = df["LATracts1"]

In [4]:
data = df.drop("LATracts1", axis=1)
feature_names = data.columns
data.head()

,CensusTract,Urban,Pop2010,OHU2010,LILATracts_1And10,LILATracts_Vehicle,HUNVFlag,LowIncomeTracts,PovertyRate,MedianFamilyIncome,...,lasnap1share,TractLOWI,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV
0,1001020100,1,1912,693,0,0,0,0,11.3,"$81,250.00",...,13.22,455.0,1622.0,217.0,14.0,0.0,14.0,45.0,44.0,6.0
1,1001020200,1,2170,743,1,0,0,1,17.9,"$49,000.00",...,12.95,802.0,888.0,1217.0,5.0,0.0,5.0,55.0,75.0,89.0
2,1001020300,1,3373,1256,0,0,0,0,15.0,"$62,609.00",...,5.87,1306.0,2576.0,647.0,17.0,5.0,11.0,117.0,87.0,99.0
3,1001020400,1,4386,1722,0,0,0,0,2.8,"$70,607.00",...,1.76,922.0,4086.0,193.0,18.0,4.0,11.0,74.0,85.0,21.0
4,1001020500,1,10766,4082,0,0,1,0,15.2,"$96,334.00",...,2.04,2242.0,8666.0,1437.0,296.0,9.0,48.0,310.0,355.0,230.0

In [5]:
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

In [6]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

ValueError: could not convert string to float: ' $26,389.00 '

In [ ]:
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

In [ ]:
sorted(zip(rf.feature_importances_, feature_names), reverse=True)